# Generated by Django 6.0.5 on 2026-05-16 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncodingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mode', models.CharField(choices=[('film', 'Film'), ('serie', 'Serie')], max_length=10)),
                ('video_codec', models.CharField(choices=[('x265', 'x265'), ('x264', 'x264'), ('av1', 'AV1')], default='x265', max_length=10)),
                ('quality_crf', models.IntegerField(default=24)),
                ('encoder_preset', models.CharField(default='medium', max_length=20)),
                ('resolution', models.CharField(choices=[('source', 'Same as source'), ('1080p', '1080p'), ('720p', '720p')], default='source', max_length=10)),
                ('audio_mode', models.CharField(choices=[('copy', 'Copy'), ('aac', 'AAC'), ('ac3', 'AC3')], default='copy', max_length=10)),
                ('container', models.CharField(default='mkv', max_length=10)),
                ('subtitle_default_lang', models.CharField(default='dan', max_length=10)),
                ('burn_forced_subs', models.BooleanField(default=False)),
                ('soft_subs', models.BooleanField(default=True)),
                ('skip_existing', models.BooleanField(default=True)),
                ('keep_folder_structure', models.BooleanField(default=True)),
                ('delete_source', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.CharField(max_length=500)),
                ('output_path', models.CharField(max_length=500)),
                ('mode', models.CharField(choices=[('film', 'Film'), ('serie', 'Serie')], max_length=10)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='encoder.encodingprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('filename', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField()),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('codec', models.CharField(blank=True, max_length=50, null=True)),
                ('resolution', models.CharField(blank=True, max_length=20, null=True)),
                ('series_title', models.CharField(blank=True, max_length=255, null=True)),
                ('season', models.IntegerField(blank=True, null=True)),
                ('episode', models.IntegerField(blank=True, null=True)),
                ('episode_title', models.CharField(blank=True, max_length=255, null=True)),
                ('selected', models.BooleanField(default=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='encoder.scansession')),
            ],
        ),
        migrations.CreateModel(
            name='SubtitleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('filename', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=10)),
                ('language_display', models.CharField(max_length=20)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('selected', models.BooleanField(default=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='encoder.videofile')),
            ],
        ),
        migrations.CreateModel(
            name='EncodeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('encoding', 'Encoding'), ('remuxing', 'Remuxing'), ('done', 'Done'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='queued', max_length=10)),
                ('progress', models.IntegerField(default=0)),
                ('output_path', models.CharField(blank=True, max_length=500, null=True)),
                ('input_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('output_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('handbrake_cmd', models.TextField(blank=True, null=True)),
                ('mkvmerge_cmd', models.TextField(blank=True, null=True)),
                ('log', models.TextField(default='')),
                ('rq_job_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='encoder.encodingprofile')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encoder.videofile')),
            ],
        ),
    ]
